### ISSUE TITLE
Show me messages based on my mood

### ISSUE THREAD

**Issue by AlexSmall96** [Markyjay/sunshine_squad_hackathon#23]
## Description
**As a** User, **I want** to input my mood and recieve feedback messages, **so that** I  can improve my mood.
## Acceptance Criteria
1.  User can choose between several mood options
2.  Feedback message changes based on user response
## Tasks
- [ ] Implement form with several options for mood
- [ ] Decide list of feedback messages and map each one to a user response
- [ ] Display appropriate message on page
- [ ] Change image of avatar depending on feedback message
