### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by ElinaBoman** [Markyjay/sunshine_squad_hackathon#39]
As a user I can see contributor of project so that I can hire them on the spot!

## Acceptance Criteria
1. All contributers have their information displayed 
2. Content is responsive 
## Tasks
- [ ] Create placeholder text for every contributor
- [ ] Add bootstrap classes to make content responsive 
- [ ] Collect information about Contributors to add in content
