### ISSUE TITLE
Puppy and Cats Carousel Feature

### ISSUE THREAD

**Issue by raneem-yad** [Markyjay/sunshine_squad_hackathon#55]
As a **user** I want **to be able to view a carousel of cute puppies and cats** so that **I can increase  joy and delight during my time on the website**

## Acceptance Criteria
1. Accessing the Carousel and Display the images
2. Navigation and Interaction
3. Automatic Rotation
4. Responsiveness and Performance

## Tasks
- [ ] Create Carousel 
- [ ] Pick images with high resolution and minimum size
- [ ] Add bootstrap classes to make content responsive 
- [ ] Add Pexel site to credits
